inherit_from:
  - .rubocop.unhound.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'vendor/bundle/**/*'
  TargetRubyVersion: 3.0.4

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
