sudo: false
language: ruby
rvm:
  - 2.3.0
  - 2.5.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: "--jobs=3 --retry=3"
cache: bundler

after_script:
    - bundle exec codeclimate-test-reporter

before_install:
  - gem update bundler
